#!/usr/bin/env python3

#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

"""The CSM Install and Upgrade Framework (IUF) CLI"""

import argparse
import atexit
import logging
import os
import shutil
import sys
import traceback

from lib.vars import *
from lib.InstallLogger import *

from lib.InstallerUtils import elapsed_time
from lib.InstallerUtils import formatted

from lib.ConfigFile import ConfigFile
from lib.ConfigFile import InvertableArgument
import lib.Config
import lib.Activity

from lib.SiteConfig import read_yaml

# Import lib.stages without the 'as stages' to prevent namespace collisions.
import lib.stages

import yaml

# pylint: disable=consider-using-f-string

install_logger = get_install_logger()

def validate_stages(config):
    """Validate that all of the various stage related args passed in are valid"""

    errors = []

    # load all of the stage variables
    begin_stage = config.args.get('begin_stage')
    end_stage = config.args.get('end_stage')
    run_stages = config.args.get('run_stages')
    skip_stages = config.args.get('skip_stages')
    state_dir = config.args.get('state_dir')
    media_dir = config.args.get('media_dir')

    config.stages.validate(state_dir, begin_stage, end_stage, run_stages, skip_stages)
    local_stages = config.stages.get(all_stages=False, list_fmt=True)
    if config.args.get("func", "") not in [process_install, process_resume,
                                           process_restart]:
        # No need to do all the error checking if we're just calling
        # 'ls', 'activity', etc.
        return

    concurrency = config.args.get("concurrency", None)
    if concurrency is not None:
        try:
            concurrency = int(concurrency)
            if concurrency != None and concurrency < 1:
                errors.append("`--concurrency` requires at least one thread.")
        except ValueError:
            errors.append("`--concurrency` requires a positive integer argument.")

    # Check if any of the stages requiring site-vars, etc are being called.
    # Note that they aren't strictly required in process-media, but all
    # the variables are resolved in that stage.  Further error-checking
    # related to this is done in SiteConfig.
    if any(stage in local_stages for stage in ["process-media",
        "update-vcs-config", "update-cfs-config", "management-nodes-rollout"]):
        if not (config.args.get("site_vars", None) or config.args.get("bootprep_config_dir", None) \
            or config.args.get("recipe_vars", None)):
            errors.append("bootprep or vcs stages were called, but none of "
                          "--site-vars/-sv, --bootprep-config-dir/-bpcd, nor --recipe-vars/-rv "
                          "were specified. At least one of them needs to be specified")

    def check_bootprep_arg(arg_name, stage):
        """Ensure that if a `sat bootprep` config was specified (and the
        stage is being run) it exists.
        """

        # activity is required, so it should never be "undefined".
        activity = config.args.get("activity", "undefined")

        arg_value = config.args.get(arg_name, None)
        param_name = "--{}".format(arg_name.replace("_", "-"))
        if not arg_value:
            return
        elif not os.path.exists(arg_value):
            errors.append(f"{param_name} {arg_value} was specified, but the file could not be found")
            return
        arg_val_basename = os.path.basename(arg_value)
        new_config_loc = os.path.join(media_dir, f".bootprep-{activity}", arg_val_basename)
        if not os.path.exists(new_config_loc):
            os.makedirs(new_config_loc)

        if os.path.exists(new_config_loc):
            if os.path.isdir(new_config_loc):
                shutil.rmtree(new_config_loc)
            else:
                os.remove(new_config_loc)
        if os.path.isdir(arg_value):
            shutil.copytree(src=arg_value, dst=new_config_loc) # copytree
        else:
            shutil.copy(arg_value, new_config_loc)

        # Change the commandline arguments to the new location, relative to media_dir to make things
        # seemless to the user.
        relative_name = f"relative_{arg_name}"
        config.args[relative_name] = os.path.basename(arg_val_basename)

    # Ensure the validity of the `--bootprep-config-dir`,
    # `--bootprep-config-managed`, and `--bootprep-config-managment` arguments.
    # Copy the bootprep files to the media directory for sat.

    # Process the `--bootprep-config-dir first.  It's not a fully-implemented option,
    # so it would be better if the fully-supported options were ran later, incase
    # there is any overwritting of files.
    check_bootprep_arg("bootprep_config_dir", "bootprep-config-dir")
    check_bootprep_arg("bootprep_config_managed", "managed-nodes-rollout")
    check_bootprep_arg("bootprep_config_management", "management-nodes-rollout")

    if errors:
        install_logger.error("Problems were encountered:")
        counter = 1
        for err in errors:
            install_logger.error("\t{}: {}".format(counter, err))
            counter += 1
        sys.exit(1)

def process_activity(config):
    state = config.args.get("state", None)
    if state:
        try:
            config.activity.state(
                timestamp=config.args.get("time", None),
                sessionid=config.args.get("argo_workflow_id", None),
                status=config.args.get("status", "n/a"),
                comment=config.args.get("comment", None),
                state=state,
                create=config.args.get("create", False)
            )
        except Exception as e:
            install_logger.error(f"{e}")
            install_logger.debug(traceback.format_exc())
            sys.exit(1)

    print(config.activity)


def process_install(config):
    """Run the install"""

    config.activity.create_activity(config)
    config.activity.run_stages(config)

    config.activity.state(state="waiting_admin")
    install_logger.info("Install completed in {}".format(elapsed_time(config.stages.installer_start)))
    summary = config.stages.get_summary()
    dashes = "----------------"
    print("{}\n{}\n{}".format(dashes, summary, dashes))


def process_list(config): #pylint: disable=unused-argument
    """Process the arguments to the list subparser"""

    if config.args.get("format", None) == "csv":
        all_stages = ','.join(config.stages.get(long=True, status=True, all_stages=True, list_fmt=True))
        summary = None
    else:
        all_stages = config.stages.get(long=True, status=True, all_stages=True, list_fmt=False)
        summary = config.stages.get_summary(load=True)

    print(all_stages)
    if summary:
        print(summary)


def process_debug_level(config):

    install_logger_file_init(config)
    if config.args.get("level", None):
        if config.args["level"] in LOG_LEVELS.keys():
            level = LOG_LEVELS[config.args["level"]]
            install_logger_stream_init(level, config.args.get("verbose", False))
        else:
            # when this runs we don't have a logger yet, just print and exit
            print("ERROR: Unrecognized log level: {}".format(config.args["level"]))
            sys.exit(1)
    else:
        install_logger_stream_init(verbose=config.args.get("verbose", False))

    log_dir_base = config.args["log_dir"]
    log_dir = os.path.join(log_dir_base, config.timestamp)
    if "func" in config.args and config.args["func"] == process_install:
        install_logger.info("All logs will be stored in {}".format(log_dir))
    return

def get_comment(text_or_list):
    """Take an list or a string and return it as a string."""
    comment = None
    if text_or_list and type(text_or_list) is list:
        comment = " ".join(text_or_list)
    elif text_or_list:
        comment = text_or_list

    return comment

def process_resume(config):
    """Pick up where we left off."""
    comment = get_comment(config.args.get("comment", None))
    activity = config.args.get("activity")
    config.stages.set_summary("comment", comment)

    stage_status = config.stages.get_stage_status(activity)
    unpaused_stage = False
    next_stage = None
    last_list_index = len(stage_status) - 1
    for ctr, stagedict in enumerate(stage_status):
        stage = stagedict["stage"]
        run_status = config.stages.run_status(stage)
        if run_status.lower() == 'paused':
            # Unpause this stage.
            unpaused_stage = stage
            break
        elif stagedict["succeeded"] is True:
            last_index = ctr + 1  if ctr + 1  <= last_list_index else ctr
            next_stage = stage_status[last_index]["stage"]

    start_at = None
    if unpaused_stage:
        start_at = unpaused_stage
    elif next_stage:
        start_at = next_stage
    else:
        print("Couldn't find a successful or paused stage to resume.")
        sys.exit(1)

    config.stages.start_at = start_at
    process_install(config)


def process_restart(config):
    """Remove the files associated with this activity and start over."""
    comment = get_comment(config.args.get("comment", None))

    # Remove the files in state_dir.
    state_dir = config.args.get("state_dir")
    for file in os.listdir(state_dir):
        fpath = os.path.join(state_dir, file)
        if os.path.isfile(fpath):
            os.unlink(fpath)

    # Remove the directories in media_dir.
    media_dir = config.args.get("media_dir")
    for file in os.listdir(media_dir):
        fpath = os.path.join(media_dir, file)
        if os.path.isdir(fpath):
            shutil.rmtree(fpath)
    config.stages.set_summary("comment", comment)
    config.stages.set_summary("ran_stages", "")
    process_install(config)


def process_abort(config):
    """Kill the running processes and abort the run."""
    activity_name = config.activity.abort_activity(config)
    install_logger.info(f"Aborted activity {activity_name}")

def update_logger_config(config):
    """
    Sets the static CmdInterface interface to "dryrun" mode
    """
    if config.dryrun:
        addLoggingLevel('DRYRUN', logging.INFO + 1)
        install_logger.dryrun("Dryrun enabled")

    addLoggingLevel('TRACE', logging.DEBUG - 1)

def check_environment_variables():
    """
    Go over a list of variables that we don't want set and remove them
    """

    CLEAN_ENV = [
        "CRAY_FORMAT",
    ]

    for var in CLEAN_ENV:
        if var in os.environ:
            del os.environ[var]

def log_state_files(config):
    if not hasattr(config, "args"):
        return
    log_dir_base = config.args["log_dir"]
    logdir = os.path.join(log_dir_base, config.timestamp)
    if hasattr(config, "stages_file"):
        if os.path.exists(config.stages_file):
            shutil.copy2(config.stages_file, logdir)


def main():
    """Main entry point."""
    check_environment_variables()
    config = lib.Config.Config()

    parser = argparse.ArgumentParser(description=
        """
       The CSM Install and Upgrade Framework (IUF) CLI.
        """
    )

    parser.add_argument("-i", "--input-file", action="store", help="""YAML input
        file used to provide arguments to `iuf`. Command line arguments will
        override entries in the input file.
        Can also be set via the IUF_INPUT_FILE environment variable.""")

    parser.add_argument("-w", "--write-input-file", action="store_true",
        help="""Create a new input file populated with default values overridden by any other command
        line options also specified. The file is named via the `-i` argument. The command exits once
        the file has been created.""")

    ### TODO, make default value product_vars.yaml 'recipe', fallback to pwd
    parser.add_argument("-a", "--activity", action="store",
        help="""Activity name.  Must be a unique identifier.
        Activity names must only contain letters (A-Za-z), numbers (0-9), periods (.), and dashes (-).
        Can also be set via the IUF_ACTIVITY environment variable.""")

    concurrency_help = """Run Argo processes concurrently. Defaults to a fully concurrent model. To
    use at most N threads, specify `concurrency N`."""
    parser.add_argument("-c", "--concurrency", action="store", default=None,
        help=concurrency_help)

    parser.add_argument("-b", "--base-dir", action="store",
        help="""Base directory for state and log file directories. Defaults to ${RBD_BASE_DIR}/iuf/[activity], where ${RBD_BASE_DIR} is /etc/cray/upgrade/csm.""")

    parser.add_argument("-s", "--state-dir", action="store",
        help="A directory used to store the current state of stages, used by `iuf` but primarily not of interest to users. Defaults to [base-dir]/state.")

    #### TODO handle both directories or list of files
    parser.add_argument("-m", "--media-dir", action="store",
        help="""Location of installation media to be used. Defaults to ${RBD_BASE_DIR}/[activity],
        where ${RBD_BASE_DIR} is /etc/cray/upgrade/csm. `iuf` cannot access installation media
        outside of ${RBD_BASE_DIR}, however input files provided by other `iuf` arguments can exist
        outside of ${RBD_BASE_DIR}.""")

    # Host to extract the media onto. Defaults to ncn-m001.
    parser.add_argument("-mh", "--media-host", action="store",
        help=argparse.SUPPRESS, default="ncn-m001")

    parser.add_argument("--log-dir", action="store",
        help="Location used to store log files. Defaults to [base-dir]/log.")

    # hide DRYRUN for now until it's production ready
    parser.add_argument("--dryrun", action=InvertableArgument, default=False, help=argparse.SUPPRESS)

    levelhelp = list(LOG_LEVELS.keys())
    levelhelp.remove('DRYRUN')
    parser.add_argument("-l", "--level", action="store", default='INFO',
        help="""Set the log message level that determines what is displayed on `iuf` standard output.
        Messages of this level or higher are displayed.""", choices=levelhelp)

    parser.add_argument("-v", "--verbose", action="store_true",
        help="generate more verbose messages")

    # TODO: The stage-dir usage could use more verbiage. We might want to add
    # this to the install docs.  Describing it in detail in the help section
    # might be inappropriate.  Essentially, we need it because not all the stages
    # are fully independent; for example, we have an unpack stage, and an
    # install stage.  The install stage needs to install what was unpacked.

    subparsers = parser.add_subparsers(title="subcommands", metavar='{run,activity,list-stages|ls,resume,restart,abort}')
    stage_list = lib.stages.get_stage_help()

    install_sp = subparsers.add_parser("run", description='Run IUF stages to execute install, upgrade and/or deploy operations for a given activity.',
        epilog="Valid stages:\n{}".format(stage_list),
        formatter_class=argparse.RawTextHelpFormatter)

    install_sp.add_argument("-b", "--begin-stage", action="store",
        help="The first stage to execute. Defaults to process-media")

    install_sp.add_argument("-e", "--end-stage", action="store",
        help="The last stage to execute.  Defaults to post-install-check")

    install_sp.add_argument("-r", "--run-stages", nargs="+", action="store",
        help="Run the specified stages only. This argument is not compatible with `-b`, `-e`, or `-s`.")

    install_sp.add_argument("-s", "--skip-stages", nargs="+", action="store",
        help="Skip the execution of the specified stages.")

    install_sp.add_argument("-F", "--force", action="store", default=False,
        #help="Force re-execution of stage operations.")
        help=argparse.SUPPRESS)

    install_sp.add_argument("-bc", "--bootprep-config-managed", action="store",
        help="""List of `sat bootprep` config files for managed (compute and
        application) nodes.""")

    install_sp.add_argument("-bm", "--bootprep-config-management", action="store",
        help="""List of `sat bootprep` config files for management NCNs.""")

    install_sp.add_argument("-bpcd", "--bootprep-config-dir", action="store",
        help="""Directory containing HPE `product_vars.yaml` and `sat bootprep` configuration files. The expected content is:
        $(BOOTPREP_CONFIG_DIR)/product_vars.yaml
        $(BOOTPREP_CONFIG_DIR)/bootprep/compute-and-uan-bootprep.yaml
        $(BOOTPREP_CONFIG_DIR)/bootprep/management-bootprep.yaml""")

    install_sp.add_argument("-rv", "--recipe-vars", action="store",
        help="""Path to a recipe variables YAML file. HPE provides the `product_vars.yaml` recipe variables file with each release.""")

    install_sp.add_argument("-sv", "--site-vars", action="store", default=False,
        help="""Path to a site variables YAML file. This file allows the user to override values defined in
        the recipe variables YAML file. Defaults to ${RBD_BASE_DIR}/${IUF_ACTIVITY}/site_vars.yaml.""")

    install_sp.add_argument("-mrs", "--managed-rollout-strategy", action="store",
        choices=["reboot", "stage"],
        default="stage",
        help="""Method to update the managed nodes. Accepted values are 'reboot' (reboot nodes _now_) or
        'stage' (set up nodes to reboot into new image after next WLM job). Defaults to 'stage'.""")

    install_sp.add_argument("-cmrp", "--concurrent-management-rollout-percentage",
        action="store", default=20,
        help="""Limit the number of management nodes that roll out
        concurrently based on the percentage specified. Must be an integer
        between 1-100. Defaults to 20 (percent).""")

    install_sp.add_argument("--limit-managed-rollout", action="store", nargs='+',
       help="""Override list used to target specific nodes only when rolling out
       managed nodes.  Arguments should be xnames or HSM node groups.""")

    install_sp.add_argument("--limit-management-rollout", action="store", nargs='+',
        default=["Management_Worker"],
        help="""Override list used to target specific role_subrole(s) only when rolling out management nodes.""")

    install_sp.add_argument("-mrp", "--mask-recipe-prods", action="store", nargs='+',
        help="""If `--recipe-vars` is specified, mask the versions found within the recipe variables YAML
        file for the specified products, such that the largest version of the package already installed on
        the system (found in the product catalog) is used instead of the version supplied in the HPC CSM
        Software Recipe. Note that the versions found via `--site-vars` (or the versions being installed)
        will override it as well.""")

    install_sp.set_defaults(func=process_install, skip_stages=list(), run_stages=list())

    list_sp = subparsers.add_parser("list-stages", description='List IUF stage information and status for a given activity specified via `-a`.', aliases=["ls"])
    list_sp.set_defaults(func=process_list)

    # create a config object to store all of the configured options in the parser

    resume_sp = subparsers.add_parser("resume", description='Resume a previously paused or failed IUF session for a given activity.')
    resume_sp.set_defaults(func=process_resume)
    resume_sp.add_argument("comment", action="store", nargs="*")

    restart_sp = subparsers.add_parser("restart", description='Restart a previously paused or failed IUF session for a given activity.')
    restart_sp.set_defaults(func=process_restart)
    restart_sp.add_argument("comment", action="store", nargs="*")

    abort_sp = subparsers.add_parser("abort", description='Abort an IUF session for a given activity after the current stage completes.')
    abort_sp.set_defaults(func=process_abort)

    # help for the comment flag should be something like,
    # """Adds a comment to the "Comment" row if the `iuf activity ...` table.
    # The option is hidden because it doesn't seem to be working in the backend.
    abort_sp.add_argument("comment", action="store", nargs="*", help=argparse.SUPPRESS)

    abort_sp.add_argument("-f", "--force", action="store_true",
        help="""Force the abort immediately.""")


    activity_sp = subparsers.add_parser("activity", description='Create, display, or annotate activity information.')
    activity_sp.add_argument("--time", help="A time value used when creating or modifying an activity entry. Must be specified and match an existing time value to modify that entry. Defaults to now.", action="store")
    activity_sp.add_argument("--create", help="Create a new activity entry.", action="store_true", default=False)
    activity_sp.add_argument("--comment", help="A comment to be associated with an activity entry.", action="store")
    activity_sp.add_argument("--status", help="A status value to be associated with an activity entry.", action="store", default="n/a", choices=lib.Activity.ACTIVITY_VALID_STATUS)
    activity_sp.add_argument("--argo-workflow-id", help="An Argo workflow identifier to be associated with an activity entry.", default=None)
    activity_sp.add_argument("state", nargs="?", help="activity state value", action="store", default=None, choices=lib.Activity.ACTIVITY_VALID_STATES)

    activity_sp.set_defaults(func=process_activity)

    configfile = ConfigFile()
    configfile.load_parser_defaults(parser)

    # allow the input file to be defined by environment variable
    env_input_file = os.getenv("IUF_INPUT_FILE", None)
    if env_input_file:
        parser.set_defaults(input_file=env_input_file)

    # parse the arguments once to get input file
    tmp_args = parser.parse_args()

    # load any defaults from the input file
    configfile.set_defaults(parser,vars(tmp_args))

    # allow the activity to be defined in the environment
    env_session = os.getenv("IUF_ACTIVITY", None)
    if env_session:
        parser.set_defaults(activity=env_session)

    # parse the command line for real
    args = parser.parse_args()

    # Check this before we do anything else so we get a reasonable error message
    if not args.activity:
        print("ERROR: --activity is required.")
        parser.print_help(sys.stderr)
        sys.exit(1)

    # Convert the args to a dict, and use that rather than the argparse
    # object.  This is so that we have a dictionary of all options, so that
    # we can more easily determine which values can be passed via an input
    # deck.
    config.args = vars(args)

    process_debug_level(config)
    update_logger_config(config)
    install_logger.debug(config.args)

    config_error = False

    if not lib.Activity.valid_activity_name(args.activity):
        install_logger.error(f"Activity {args.activity} invalid. Names must only contain letters, numbers, periods, and dashes")
        config_error = True

    if len(sys.argv) < 2:
        install_logger.error("{} requires at least 1 argument".format(sys.argv[0]))
        config_error = True

    if config_error:
        parser.print_help(sys.stderr)
        sys.exit(1)

    config.stages = lib.stages.Stages(stage_dict=STAGE_DICT, state_dir=config.args["state_dir"])
    validate_stages(config)

    if config.args["write_input_file"]:
        configfile.write(config.args)

    atexit.register(log_state_files, config)

    try:
        args.func(config)
    except AttributeError:
        install_logger.error("A subcommand was not specified.")
        sys.exit(1)
    except Exception as e:
        install_logger.error("An unexpected error occurred: {}".format(e))
        raise

if __name__ == "__main__":
    main()
